/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_2019_02_05_frame;

import java.util.Random;

/**
 *
 * @author adria
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextAlumno1 = new javax.swing.JTextField();
        jTextAsist1 = new javax.swing.JTextField();
        jTextTareas1 = new javax.swing.JTextField();
        jTextProy1 = new javax.swing.JTextField();
        jTextExamen1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextAlumno2 = new javax.swing.JTextField();
        jTextAsist2 = new javax.swing.JTextField();
        jTextTareas2 = new javax.swing.JTextField();
        jTextProy2 = new javax.swing.JTextField();
        jTextExamen2 = new javax.swing.JTextField();
        jLabCalif1 = new javax.swing.JLabel();
        jLabCalif3 = new javax.swing.JLabel();
        jTextAlumno3 = new javax.swing.JTextField();
        jTextAsist3 = new javax.swing.JTextField();
        jTextTareas3 = new javax.swing.JTextField();
        jTextProy3 = new javax.swing.JTextField();
        jTextExamen3 = new javax.swing.JTextField();
        jLabCalif2 = new javax.swing.JLabel();
        jLabPromCalif = new javax.swing.JLabel();
        jLabPromExamen = new javax.swing.JLabel();
        jLabPromProy = new javax.swing.JLabel();
        jLabPromTareas = new javax.swing.JLabel();
        jLabPromAsist = new javax.swing.JLabel();
        jButCalcular = new javax.swing.JButton();
        jButAleatorio = new javax.swing.JButton();
        jButBorrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextExamen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExamen1ActionPerformed(evt);
            }
        });

        jLabel1.setText("NOMBRE");

        jLabel2.setText("TAREAS");

        jLabel3.setText("ASIST");

        jLabel4.setText("PROYECTOS");

        jLabel5.setText("EXAMEN");

        jLabel6.setText("CALIFICACION");

        jTextExamen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExamen2ActionPerformed(evt);
            }
        });

        jLabCalif1.setBackground(new java.awt.Color(0, 204, 255));
        jLabCalif1.setText(" ");
        jLabCalif1.setOpaque(true);

        jLabCalif3.setBackground(new java.awt.Color(0, 204, 255));
        jLabCalif3.setText(" ");
        jLabCalif3.setOpaque(true);

        jTextExamen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExamen3ActionPerformed(evt);
            }
        });

        jLabCalif2.setBackground(new java.awt.Color(0, 204, 255));
        jLabCalif2.setText(" ");
        jLabCalif2.setOpaque(true);

        jLabPromCalif.setBackground(new java.awt.Color(0, 255, 51));
        jLabPromCalif.setText(" ");
        jLabPromCalif.setOpaque(true);

        jLabPromExamen.setBackground(new java.awt.Color(0, 204, 204));
        jLabPromExamen.setText(" ");
        jLabPromExamen.setOpaque(true);

        jLabPromProy.setBackground(new java.awt.Color(0, 204, 204));
        jLabPromProy.setText(" ");
        jLabPromProy.setOpaque(true);

        jLabPromTareas.setBackground(new java.awt.Color(0, 204, 204));
        jLabPromTareas.setText("  ");
        jLabPromTareas.setOpaque(true);

        jLabPromAsist.setBackground(new java.awt.Color(0, 204, 204));
        jLabPromAsist.setText(" ");
        jLabPromAsist.setOpaque(true);

        jButCalcular.setText("CALCULAR");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButAleatorio.setText("ALEATORIO");
        jButAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatorioActionPerformed(evt);
            }
        });

        jButBorrar.setText("BORRAR");
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });

        jLabel7.setText("PROMEDIO:");

        jLabel8.setText("PROMEDIO GENERAL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextAlumno3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(jTextAlumno1)
                        .addComponent(jTextAlumno2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(19, 19, 19)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabPromAsist, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jLabPromProy, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextAsist1)
                                            .addComponent(jTextAsist2)
                                            .addComponent(jTextAsist3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextTareas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextTareas2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextTareas3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabPromTareas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel2)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextProy1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextProy2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(jTextProy3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextExamen3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextExamen2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabPromExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabCalif1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabCalif2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabCalif3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabPromCalif, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButCalcular)
                .addGap(18, 18, 18)
                .addComponent(jButAleatorio)
                .addGap(28, 28, 28)
                .addComponent(jButBorrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabCalif1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextTareas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextProy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabCalif2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextTareas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextProy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextExamen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextAsist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextAsist2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabCalif3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButCalcular)
                                    .addComponent(jButBorrar)
                                    .addComponent(jButAleatorio))
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabPromCalif)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextProy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextExamen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTareas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAsist3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabPromExamen)
                            .addComponent(jLabPromProy)
                            .addComponent(jLabPromTareas)
                            .addComponent(jLabPromAsist))
                        .addGap(110, 110, 110))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextExamen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExamen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExamen1ActionPerformed

    private void jTextExamen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExamen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExamen2ActionPerformed

    private void jTextExamen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExamen3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExamen3ActionPerformed

    private void jButAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatorioActionPerformed
        // BOTON ALEATORIO
        Random azar = new Random();
        
        String [] nom = {"Juan","Maria","Luis","Diana", "Pedro", "Laura", "Carlos","Ulises","Diego","Patricia"}; 
        String [] ape = {"Garcia","Mendez","Rodriguez","Martinez","Perez","Gomez","Blanco","Lopez"};
        
        jTextAlumno1.setText(nom[azar.nextInt(nom.length)]+" "+(ape[azar.nextInt(ape.length)]));
        jTextAlumno2.setText(nom[azar.nextInt(nom.length)]+" "+(ape[azar.nextInt(ape.length)]));
        jTextAlumno3.setText(nom[azar.nextInt(nom.length)]+" "+(ape[azar.nextInt(ape.length)]));
        
        
        jTextAsist1.setText(40+azar.nextInt(61)+"");
        jTextAsist2.setText(40+azar.nextInt(61)+"");
        jTextAsist3.setText(40+azar.nextInt(61)+"");
        
        jTextTareas1.setText(40+azar.nextInt(61)+"");
        jTextTareas2.setText(40+azar.nextInt(61)+"");
        jTextTareas3.setText(40+azar.nextInt(61)+"");
        
        jTextProy1.setText(40+azar.nextInt(61)+"");
        jTextProy2.setText(40+azar.nextInt(61)+"");
        jTextProy3.setText(40+azar.nextInt(61)+"");
        
        jTextExamen1.setText(40+azar.nextInt(61)+"");
        jTextExamen2.setText(40+azar.nextInt(61)+"");
        jTextExamen3.setText(40+azar.nextInt(61)+"");
        
        
        
        
    }//GEN-LAST:event_jButAleatorioActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        // BOTON BORRAR
        jTextAlumno1.setText("");
        jTextAlumno2.setText("");
        jTextAlumno3.setText("");
        
        
        jTextAsist1.setText("");
        jTextAsist2.setText("");
        jTextAsist3.setText("");
        
        jTextTareas1.setText("");
        jTextTareas2.setText("");
        jTextTareas3.setText("");
        
        jTextProy1.setText("");
        jTextProy2.setText("");
        jTextProy3.setText("");
        
        jTextExamen1.setText("");
        jTextExamen2.setText("");
        jTextExamen3.setText("");
        
    }//GEN-LAST:event_jButBorrarActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // BOTON CALCULAR:
        String nombre;
        int asist, tareas, proy, examen;
        
        nombre = jTextAlumno1.getText();
        asist = Integer.parseInt(jTextAsist1.getText());
        tareas = Integer.parseInt(jTextTareas1.getText());
        proy = Integer.parseInt(jTextProy1.getText());
        examen = Integer.parseInt(jTextExamen1.getText()); 
        
        Alumno uno = new Alumno();
        
        uno.setNombre(nombre);
        uno.setAsistencias(asist);
        uno.setTareas(tareas);
        uno.setProyectos(proy);
        uno.setExamen(examen);
        
        jLabCalif1.setText(uno.calificacion()+"");
       
        
        Alumno dos = new Alumno ()jTextAlumno2.getText(),
                                  Integer.parseInt(jTextAsist2.getText()),
                                  Integer.parseInt(jTextTareas2.getText()),
                                  Integer.parseInt(jTextProy2.getText()),
                                  Integer.parseInt(jTextExamen2.getText());
                                  
        jLabCalif1.setText(uno.calificacion()+"");
                                  
         
               
    }//GEN-LAST:event_jButCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorio;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JLabel jLabCalif1;
    private javax.swing.JLabel jLabCalif2;
    private javax.swing.JLabel jLabCalif3;
    private javax.swing.JLabel jLabPromAsist;
    private javax.swing.JLabel jLabPromCalif;
    private javax.swing.JLabel jLabPromExamen;
    private javax.swing.JLabel jLabPromProy;
    private javax.swing.JLabel jLabPromTareas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextAlumno1;
    private javax.swing.JTextField jTextAlumno2;
    private javax.swing.JTextField jTextAlumno3;
    private javax.swing.JTextField jTextAsist1;
    private javax.swing.JTextField jTextAsist2;
    private javax.swing.JTextField jTextAsist3;
    private javax.swing.JTextField jTextExamen1;
    private javax.swing.JTextField jTextExamen2;
    private javax.swing.JTextField jTextExamen3;
    private javax.swing.JTextField jTextProy1;
    private javax.swing.JTextField jTextProy2;
    private javax.swing.JTextField jTextProy3;
    private javax.swing.JTextField jTextTareas1;
    private javax.swing.JTextField jTextTareas2;
    private javax.swing.JTextField jTextTareas3;
    // End of variables declaration//GEN-END:variables
}
