/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_18131253_examen2;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author adria
 */
public class JFrameVisual1 extends javax.swing.JFrame {

    /**
     * Creates new form JFrameVisual1
     */
    public JFrameVisual1() {
        initComponents();
        
        JOptionPane.showMessageDialog(null, "Bienvenido :)!!");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButSalir = new javax.swing.JButton();
        jButSuma = new javax.swing.JButton();
        jButResta = new javax.swing.JButton();
        jButEjemplo = new javax.swing.JButton();
        jButAleatorio = new javax.swing.JButton();
        jButBorrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextGalon1 = new javax.swing.JTextField();
        jTextGalon2 = new javax.swing.JTextField();
        jLabResultado = new javax.swing.JLabel();
        jTextBarril1 = new javax.swing.JTextField();
        jTextBarril2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Calculadora de Petroleo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jButSalir.setText("Salir");
        jButSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        jButSuma.setText("Suma");
        jButSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSumaActionPerformed(evt);
            }
        });
        getContentPane().add(jButSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jButResta.setText("Resta");
        jButResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRestaActionPerformed(evt);
            }
        });
        getContentPane().add(jButResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });
        getContentPane().add(jButEjemplo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        jButAleatorio.setText("Aleatorio");
        jButAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jButAleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jButBorrar.setText("Borrar");
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel3.setText("Resultado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel4.setText("Galon(es)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel5.setText("Barril(es)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jTextGalon1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextGalon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 60, -1));

        jTextGalon2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextGalon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 60, -1));

        jLabResultado.setBackground(new java.awt.Color(255, 204, 102));
        jLabResultado.setOpaque(true);
        getContentPane().add(jLabResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 330, 20));

        jTextBarril1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextBarril1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 60, -1));

        jTextBarril2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextBarril2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_18131253_examen2/FrameFondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButSalirActionPerformed

    private void jButSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSumaActionPerformed
        // TODO add your handling code here:
        Petroleo Petroleo1 = new Petroleo();
        Petroleo Petroleo2 = new Petroleo();
        
        Petroleo SumaTotal;
        
        Petroleo1.setGalon(Integer.parseInt(jTextGalon1.getText()));
        Petroleo1.setBarril(Integer.parseInt(jTextBarril1.getText()));
        
        Petroleo2.setGalon(Integer.parseInt(jTextGalon2.getText()));
        Petroleo2.setBarril(Integer.parseInt(jTextBarril2.getText()));
        
        SumaTotal = Petroleo1.Suma(Petroleo2);
        jLabResultado.setText(SumaTotal+"");
        
        
    }//GEN-LAST:event_jButSumaActionPerformed

    private void jButRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRestaActionPerformed
        // TODO add your handling code here:
        Petroleo Galon1 = new Petroleo();
        Petroleo Barril1 = new Petroleo();
        Petroleo Galon2 = new Petroleo();
        Petroleo Barril2 = new Petroleo();
        Petroleo Suma1, Suma2;
        Petroleo RestaTotal = new Petroleo();

        Barril1.setBarril(Integer.parseInt(jTextBarril1.getText()));
        Galon1.setGalon(Integer.parseInt(jTextGalon1.getText()));

        Suma1 = Galon1.Resta(Barril1);

        Barril2.setBarril(Integer.parseInt(jTextBarril2.getText()));
        Galon2.setGalon(Integer.parseInt(jTextGalon2.getText()));

        Suma2 = Galon2.Resta(Barril2);

        RestaTotal = Suma1.Resta(Suma2);

        jLabResultado.setText("Resta: "+RestaTotal);
    }//GEN-LAST:event_jButRestaActionPerformed

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        jTextGalon1.setText("17");
        jTextBarril1.setText("3");

        jTextGalon2.setText("30");
        jTextBarril2.setText("2");
    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatorioActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();

        jTextGalon1.setText(azar.nextInt(999)+"");
        jTextBarril1.setText(azar.nextInt(999)+"");

        jTextGalon2.setText(azar.nextInt(999)+"");
        jTextBarril2.setText(azar.nextInt(999)+"");

    }//GEN-LAST:event_jButAleatorioActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        // TODO add your handling code here:
        jTextGalon1.setText("");
        jTextBarril1.setText("");

        jTextGalon2.setText("");
        jTextBarril2.setText("");

        jLabResultado.setText("");
    }//GEN-LAST:event_jButBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVisual1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVisual1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVisual1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVisual1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVisual1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorio;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButResta;
    private javax.swing.JButton jButSalir;
    private javax.swing.JButton jButSuma;
    private javax.swing.JLabel jLabResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextBarril1;
    private javax.swing.JTextField jTextBarril2;
    private javax.swing.JTextField jTextGalon1;
    private javax.swing.JTextField jTextGalon2;
    // End of variables declaration//GEN-END:variables
}
