/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_2019_05_23_buscarnumero;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author aa629
 */
public class JFrameTablero extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form JFrameTablero
     */
    MiBoton [] fichas = new MiBoton[20];
    Random azar = new Random();
    int numeroABuscar;
    int intentos;
    
    
    public JFrameTablero() {
        initComponents();
        
        int x=30;
        int y=50;
        
        setSize(550,550);
        
        MiBoton.setColor(2);
        
        for(int i=0; i<fichas.length; i++)
        {
            fichas[i] = new MiBoton(azar.nextInt(100));
        
            fichas[i].setLocation(x, y);
            

            x+=100;
            
            if((i+1)%5 == 0)
            {
                x = 30;
                y += 100;
            }
            
            fichas[i].addActionListener(this);
            
            add(fichas[i]);
            
          
        }
        
       numeroABuscar = fichas[azar.nextInt(fichas.length)].getNumero();
       intentos = 0;
       
       jLabBuscar.setText(numeroABuscar+"");
       jLabIntentos.setText(intentos+"");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabBuscar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabIntentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("NUMERO A  BUSCAR:");

        jLabBuscar.setBackground(new java.awt.Color(255, 255, 0));
        jLabBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabBuscar.setText("  ");
        jLabBuscar.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("INTENTOS:");

        jLabIntentos.setBackground(new java.awt.Color(255, 255, 0));
        jLabIntentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabIntentos.setText("  ");
        jLabIntentos.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabBuscar)
                    .addComponent(jLabel3)
                    .addComponent(jLabIntentos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTablero().setVisible(true);
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        MiBoton boton = (MiBoton)e.getSource();
        
        boton.mostrar();
        boton.setEnabled(false);
        
        intentos++;
        
        jLabIntentos.setText(intentos+"");
        
        if(boton.getNumero() == numeroABuscar)
        {
            JOptionPane.showMessageDialog(rootPane, "YA LO ENCONTRO");
            
            for(MiBoton b: fichas)
                b.mostrar();
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabBuscar;
    private javax.swing.JLabel jLabIntentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
