/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_2019_03_05_aplicacionresultante;

import java.text.DecimalFormat;
import java.util.Random;

/**
 *
 * @author aa612
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    DecimalFormat df = new DecimalFormat("###,##0.00");
    Vector uno = null, dos = null, tres = null;
    
    public NewJFrame() {
        initComponents();
    }

    public void crearVectores()
    {
        try
        {
        uno = new Vector();
        uno.setMagnitude(Double.parseDouble(jTextMag1.getText()));
        uno.setAngulo(Double.parseDouble(jTextAngulo1.getText()));
        
        dos = new Vector(Double.parseDouble(jTextMag2.getText()), 
                                Double.parseDouble(jTextAngulo2.getText()));
        }
        
        catch(Exception ex)
        {
            uno = new Vector();
            dos = new Vector();
            
        }
    }
    
    public void mostrarResultante()
    {
        jLabMagR.setText(df.format(tres.getMagnitude()));
        jLabAnguloR.setText(df.format(tres.getAngulo()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextMag1 = new javax.swing.JTextField();
        jTextAngulo1 = new javax.swing.JTextField();
        jTextMag2 = new javax.swing.JTextField();
        jTextAngulo2 = new javax.swing.JTextField();
        jButSuma = new javax.swing.JButton();
        jButResta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabMagR = new javax.swing.JLabel();
        jLabAnguloR = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButVRV1 = new javax.swing.JButton();
        jButVRV2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAngulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAngulo1ActionPerformed(evt);
            }
        });

        jTextMag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMag2ActionPerformed(evt);
            }
        });

        jTextAngulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAngulo2ActionPerformed(evt);
            }
        });

        jButSuma.setText("+");
        jButSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSumaActionPerformed(evt);
            }
        });

        jButResta.setText("-");
        jButResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRestaActionPerformed(evt);
            }
        });

        jLabel1.setText("MAGNITUD:");

        jLabel2.setText("ANGULO:");

        jLabel3.setText("VECTOR 1");

        jLabel4.setText("VECTOR 2");

        jLabel5.setText("=");

        jLabMagR.setBackground(new java.awt.Color(0, 102, 255));
        jLabMagR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabMagR.setText(" ");
        jLabMagR.setOpaque(true);

        jLabAnguloR.setBackground(new java.awt.Color(0, 102, 255));
        jLabAnguloR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabAnguloR.setText(" ");
        jLabAnguloR.setOpaque(true);

        jLabel8.setText("RESULTANTE");

        jButVRV1.setText("VR ---> V1");
        jButVRV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVRV1ActionPerformed(evt);
            }
        });

        jButVRV2.setText("ALEATORIOS");
        jButVRV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVRV2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextAngulo1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextMag1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButResta)))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextMag2)
                                    .addComponent(jTextAngulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4)))
                    .addComponent(jButVRV2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButVRV1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jLabMagR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabAnguloR, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextMag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButSuma)
                            .addComponent(jLabel1)
                            .addComponent(jLabMagR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAngulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAngulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButResta)
                            .addComponent(jLabel2)
                            .addComponent(jLabAnguloR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButVRV1)
                    .addComponent(jButVRV2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAngulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAngulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAngulo1ActionPerformed

    private void jTextMag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMag2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMag2ActionPerformed

    private void jTextAngulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAngulo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAngulo2ActionPerformed

    private void jButSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSumaActionPerformed
        // BOTON SUMA:
        crearVectores();     
        
        tres = uno.suma(dos);
        
        mostrarResultante();
    }//GEN-LAST:event_jButSumaActionPerformed

    private void jButRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRestaActionPerformed
        // BOTON RESTA
        crearVectores();     
        
        tres = uno.resta(dos);
        
        mostrarResultante();
    }//GEN-LAST:event_jButRestaActionPerformed

    private void jButVRV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVRV1ActionPerformed
        // TODO add your handling code here:
        jTextMag1.setText(jLabMagR.getText());
        jTextAngulo1.setText(jLabAnguloR.getText());
        
        jTextMag2.setText("");
        jTextAngulo2.setText("");
        
        jLabMagR.setText("");
        jLabAnguloR.setText("");
        
    }//GEN-LAST:event_jButVRV1ActionPerformed

    
    private void jButVRV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVRV2ActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        
        jTextMag1.setText(azar.nextInt(500)+"");
        jTextMag2.setText(azar.nextInt(500)+"");
        
        jTextAngulo1.setText(azar.nextInt(360)+"");
        jTextAngulo2.setText(azar.nextInt(360)+"");
        
        jLabMagR.setText("");
        jLabAnguloR.setText("");
    }//GEN-LAST:event_jButVRV2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButResta;
    private javax.swing.JButton jButSuma;
    private javax.swing.JButton jButVRV1;
    private javax.swing.JButton jButVRV2;
    private javax.swing.JLabel jLabAnguloR;
    private javax.swing.JLabel jLabMagR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextAngulo1;
    private javax.swing.JTextField jTextAngulo2;
    private javax.swing.JTextField jTextMag1;
    private javax.swing.JTextField jTextMag2;
    // End of variables declaration//GEN-END:variables
}
