
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author adria
 *
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal()
    {
        initComponents();
        jButObjeto.setText("Objeto");
    }
    
    public static double volumenCilindro(double r, double h)
    {
        double v;
        v=Math.PI * Math.pow(r,2) * h;
        return v;
    }
    public static double areaCilindro (double r, double h)
    {
       return 2 * Math.PI * r * (r + h);    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextRadio = new javax.swing.JTextField();
        jTextAltura = new javax.swing.JTextField();
        jButCalcular = new javax.swing.JButton();
        jButBorrar = new javax.swing.JButton();
        jButAleatorio = new javax.swing.JButton();
        jLabArea = new javax.swing.JLabel();
        jLabVolumen = new javax.swing.JLabel();
        jButFunciones = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButObjeto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("RADIO:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("ALTURA:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("AREA=");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("VOLUMEN=");

        jButCalcular.setBackground(new java.awt.Color(0, 255, 255));
        jButCalcular.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButCalcular.setText("CALCULAR");
        jButCalcular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButBorrar.setBackground(new java.awt.Color(0, 0, 255));
        jButBorrar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButBorrar.setText("BORRAR");
        jButBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });

        jButAleatorio.setBackground(new java.awt.Color(255, 0, 0));
        jButAleatorio.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jButAleatorio.setText("ALEATORIO");
        jButAleatorio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatorioActionPerformed(evt);
            }
        });

        jLabArea.setBackground(new java.awt.Color(255, 255, 0));
        jLabArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabArea.setOpaque(true);

        jLabVolumen.setBackground(new java.awt.Color(0, 255, 0));
        jLabVolumen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabVolumen.setOpaque(true);

        jButFunciones.setBackground(new java.awt.Color(255, 51, 204));
        jButFunciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButFunciones.setText("FUNCIONES");
        jButFunciones.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButFuncionesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CÁLCULO DE ÁREA Y VOLUMEN DE UN CILINDRO ");

        jButObjeto.setBackground(new java.awt.Color(153, 0, 153));
        jButObjeto.setText("b");
        jButObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButObjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextAltura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jTextRadio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabVolumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButAleatorio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1))
                    .addComponent(jTextRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButFunciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3))
                            .addComponent(jLabArea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        //DECLARACION DE VARIABLES 
        double radio, altura, area, volumen;
        //DATOS DE ENTRADA
        radio=Double.parseDouble(jTextRadio.getText());
        altura=Double.parseDouble(jTextAltura.getText());
        //PROCESO
        volumen = Math.PI * Math.pow(radio,2) * altura;
        area = 2 * Math.PI * radio * (radio + altura);
        //DATOS DE SALIDA 
        jLabArea.setText(area+"");
        jLabVolumen.setText(volumen+"");
        
        //DESEAR QUE EL COLOR CORRESPONDIDO AL BOTON SE AGREGUE AL COLOR DEL FONDO DEL TEXTO DE AREA Y VOLUMEN:
        jLabArea.setBackground(jButCalcular.getBackground());
        jLabVolumen.setBackground(jButCalcular.getBackground());
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        // TODO add your handling code here:
        jTextRadio.setText("");
        jTextAltura.setText("");
        jLabArea.setText("");
        jLabVolumen.setText("");
    }//GEN-LAST:event_jButBorrarActionPerformed

    private void jButAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatorioActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        
        jTextRadio.setText(azar.nextInt(1000)/10.0+"");
        jTextAltura.setText(azar.nextInt(5000)/10.0+"");
        jLabArea.setText("");
        jLabVolumen.setText("");
    }//GEN-LAST:event_jButAleatorioActionPerformed

    private void jButFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButFuncionesActionPerformed
        // TODO add your handling code here:
        //DECLARACION DE VARIABLES 
        double radio, altura, area, volumen;
        //DATOS DE ENTRADA
        radio=Double.parseDouble(jTextRadio.getText());
        altura=Double.parseDouble(jTextAltura.getText());
        //PROCESO
        volumen = volumenCilindro(radio,altura);
        area = areaCilindro(radio,altura);
        //DATOS DE SALIDA 
        jLabArea.setText(area+"");
        jLabVolumen.setText(volumen+"");
        
        //DESEAR QUE EL COLOR CORRESPONDIDO AL BOTON SE AGREGUE AL COLOR DEL FONDO DEL TEXTO DE AREA Y VOLUMEN:
        jLabArea.setBackground(jButFunciones.getBackground());
        jLabVolumen.setBackground(jButFunciones.getBackground());
    }//GEN-LAST:event_jButFuncionesActionPerformed

    private void jButObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButObjetoActionPerformed
        // TODO add your handling code here:
         double radio, altura, area, volumen;
        //DATOS DE ENTRADA
        radio=Double.parseDouble(jTextRadio.getText());
        altura=Double.parseDouble(jTextAltura.getText());
        //PROCESO
        Cilindro x = new Cilindro ();
        
        volumen = volumenCilindro(radio,altura);
        area = areaCilindro(radio,altura);
        //DATOS DE SALIDA 
        jLabArea.setText(x.area()+"");
        jLabVolumen.setText(x.volumen()+"");
        
        //DESEAR QUE EL COLOR CORRESPONDIDO AL BOTON SE AGREGUE AL COLOR DEL FONDO DEL TEXTO DE AREA Y VOLUMEN:
        jLabArea.setBackground(jButObjeto.getBackground());
        jLabVolumen.setBackground(jButObjeto.getBackground());
    }//GEN-LAST:event_jButObjetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorio;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButFunciones;
    private javax.swing.JButton jButObjeto;
    private javax.swing.JLabel jLabArea;
    private javax.swing.JLabel jLabVolumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextAltura;
    private javax.swing.JTextField jTextRadio;
    // End of variables declaration//GEN-END:variables
}
