/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_18131253_proyecto_04;

import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adria
 */
public class jFrameVisual extends javax.swing.JFrame {

    DefaultTableModel modelo;
    Poligono poligono;
    Random azar = new Random();
    JFileChooser jfch = new JFileChooser();
    
    /**
     * Creates new form jFrameVisual
     */
    public jFrameVisual() {
        initComponents();
        JOptionPane.showMessageDialog(null, "            Bienvenido :)!!"
                + "\n                Proyecto 4"
                + "\n    Jesus Adrian Lopez Luevanos"
                + "\n         N° control: 18131253");
        this.setLocationRelativeTo(null);
        
        
        modelo = (DefaultTableModel)jTablePoligono.getModel();
        jTablePoligono.setShowGrid(true);
        
        poligono = new Poligono();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void creador(int posicion)
    {
        poligono.setPosicion(Integer.parseInt(modelo.getValueAt(posicion, 0)+""));
        poligono.setLadoX(Integer.parseInt(modelo.getValueAt(posicion, 1)+""));
        poligono.setLadoY(Integer.parseInt(modelo.getValueAt(posicion, 2)+""));
        poligono.setLadoX2(Integer.parseInt(modelo.getValueAt(posicion, 3)+""));
        poligono.setLadoY2(Integer.parseInt(modelo.getValueAt(posicion, 4)+""));
        
        
        if(jRadioAmarillo.isSelected())
            poligono.setColor(Color.yellow);
        
        if(jRadioAzul.isSelected())
            poligono.setColor(Color.BLUE);
        
        if(jRadioRojo.isSelected())
            poligono.setColor(Color.RED);
        
        if(jRadioRosa.isSelected())
            poligono.setColor(Color.PINK);
        
        if(jRadioNaranja.isSelected())
            poligono.setColor(Color.ORANGE);
        
        if(jRadioCyan.isSelected())
            poligono.setColor(Color.CYAN);
        
        if(jRadioVerde.isSelected())
            poligono.setColor(Color.GREEN);
        
        if(jRadioGris.isSelected())
            poligono.setColor(Color.GRAY);
        
        poligono.dibujo(jPanelDibujar);
    }
        
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jSpinDibujar = new javax.swing.JSpinner();
        jSpinNumero = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jButGrabar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextLadoY = new javax.swing.JTextField();
        jTextLadoX = new javax.swing.JTextField();
        jButAleatorio = new javax.swing.JButton();
        jButDibujar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePoligono = new javax.swing.JTable();
        jRadioCyan = new javax.swing.JRadioButton();
        jRadioAzul = new javax.swing.JRadioButton();
        jRadioRosa = new javax.swing.JRadioButton();
        jRadioAmarillo = new javax.swing.JRadioButton();
        jRadioRojo = new javax.swing.JRadioButton();
        jRadioVerde = new javax.swing.JRadioButton();
        jRadioGris = new javax.swing.JRadioButton();
        jRadioNaranja = new javax.swing.JRadioButton();
        jSpinPosicion = new javax.swing.JSpinner();
        jButAsignacion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelDibujar = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jTextLadoX2 = new javax.swing.JTextField();
        jTextLadoY2 = new javax.swing.JTextField();
        jButEjemplo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenuItem();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenuAbrir = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lado Y");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jSpinDibujar.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, null, Integer.valueOf(1)));
        getContentPane().add(jSpinDibujar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 50, 30));

        jSpinNumero.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, null, Integer.valueOf(1)));
        jSpinNumero.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinNumeroStateChanged(evt);
            }
        });
        getContentPane().add(jSpinNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 50, 30));

        jLabel3.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Elije un Color");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(jButGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 90, -1));

        jLabel4.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Posicion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lado x");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));
        getContentPane().add(jTextLadoY, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 70, 30));
        getContentPane().add(jTextLadoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 70, 30));

        jButAleatorio.setText("Aleatorio");
        jButAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jButAleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 90, -1));

        jButDibujar.setText("Dibujar");
        jButDibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDibujarActionPerformed(evt);
            }
        });
        getContentPane().add(jButDibujar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 80, -1));

        jTablePoligono.setBackground(new java.awt.Color(0, 0, 0));
        jTablePoligono.setForeground(new java.awt.Color(255, 255, 255));
        jTablePoligono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Poligno", "Lado X", "Lado Y", "Lado X2", "Lado Y2", "Color"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePoligono.setOpaque(false);
        jScrollPane1.setViewportView(jTablePoligono);
        if (jTablePoligono.getColumnModel().getColumnCount() > 0) {
            jTablePoligono.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTablePoligono.getColumnModel().getColumn(1).setPreferredWidth(25);
            jTablePoligono.getColumnModel().getColumn(2).setPreferredWidth(25);
            jTablePoligono.getColumnModel().getColumn(3).setPreferredWidth(25);
            jTablePoligono.getColumnModel().getColumn(4).setPreferredWidth(25);
            jTablePoligono.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 350, 330));

        buttonGroup1.add(jRadioCyan);
        jRadioCyan.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jRadioCyan.setForeground(new java.awt.Color(0, 255, 255));
        jRadioCyan.setText("Cyan");
        jRadioCyan.setOpaque(false);
        jRadioCyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCyanActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioCyan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        buttonGroup1.add(jRadioAzul);
        jRadioAzul.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        jRadioAzul.setForeground(new java.awt.Color(0, 102, 255));
        jRadioAzul.setText("Azul");
        jRadioAzul.setOpaque(false);
        jRadioAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAzulActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 70, -1));

        buttonGroup1.add(jRadioRosa);
        jRadioRosa.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jRadioRosa.setForeground(new java.awt.Color(255, 0, 255));
        jRadioRosa.setText("Rosa");
        jRadioRosa.setOpaque(false);
        jRadioRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRosaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        buttonGroup1.add(jRadioAmarillo);
        jRadioAmarillo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jRadioAmarillo.setForeground(new java.awt.Color(255, 255, 0));
        jRadioAmarillo.setText("Amarillo");
        jRadioAmarillo.setOpaque(false);
        jRadioAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAmarilloActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        buttonGroup1.add(jRadioRojo);
        jRadioRojo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jRadioRojo.setForeground(new java.awt.Color(255, 0, 0));
        jRadioRojo.setText("Rojo");
        jRadioRojo.setOpaque(false);
        jRadioRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRojoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 60, -1));

        buttonGroup1.add(jRadioVerde);
        jRadioVerde.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jRadioVerde.setForeground(new java.awt.Color(0, 255, 0));
        jRadioVerde.setText("Verde");
        jRadioVerde.setOpaque(false);
        jRadioVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioVerdeActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        buttonGroup1.add(jRadioGris);
        jRadioGris.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jRadioGris.setForeground(new java.awt.Color(204, 204, 204));
        jRadioGris.setText("Gris");
        jRadioGris.setOpaque(false);
        jRadioGris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGrisActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 50, -1));

        buttonGroup1.add(jRadioNaranja);
        jRadioNaranja.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jRadioNaranja.setForeground(new java.awt.Color(255, 153, 0));
        jRadioNaranja.setText("Naranja");
        jRadioNaranja.setOpaque(false);
        jRadioNaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNaranjaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioNaranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jSpinPosicion.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, null, Integer.valueOf(1)));
        getContentPane().add(jSpinPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 50, 30));

        jButAsignacion.setText("Asignacion");
        jButAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAsignacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 90, -1));

        jScrollPane2.setViewportView(jPanelDibujar);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 320, 330));

        jLabel7.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("N° Poligonos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        getContentPane().add(jTextLadoX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 70, 30));
        getContentPane().add(jTextLadoY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 70, 30));

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });
        getContentPane().add(jButEjemplo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_18131253_proyecto_04/Fondo.jpg"))); // NOI18N
        jLabel1.setText("Lado X");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1128, 540));

        jMenu1.setText("Archivo");

        jMenuNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuNuevo.setText("Nuevo");
        jMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNuevo);

        jMenuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuGuardar);

        jMenuAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAbrir.setText("Abrir");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAbrir);

        jMenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informacion");

        jMenu3.setText("Proyecto 4");
        jMenu2.add(jMenu3);

        jMenu4.setText("Adrian Luevanos");
        jMenu2.add(jMenu4);

        jMenu5.setText("# 18131253");
        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        // TODO add your handling code here:
        int i = Integer.parseInt(jSpinPosicion.getValue()+"");
        
        modelo.setValueAt(i, i-1, 0);
        modelo.setValueAt(jTextLadoX.getText(), i-1, 1);
        modelo.setValueAt(jTextLadoY.getText(), i-1, 2);
        modelo.setValueAt(jTextLadoX2.getText(), i-1, 3);
        modelo.setValueAt(jTextLadoY2.getText(), i-1, 4);
       
        if(i<Integer.parseInt(jSpinNumero.getValue()+""))
            i++;
        else
            i=1;
        
        jSpinPosicion.setValue(i);
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jButAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatorioActionPerformed
        // TODO add your handling code here:
         for(int i=1; i<=Integer.parseInt(jSpinNumero.getValue()+"");i++)
        {
            
            modelo.setValueAt(i, i-1, 0);
            modelo.setValueAt(1+azar.nextInt(250), i-1, 1);
            modelo.setValueAt(1+azar.nextInt(250), i-1, 2);
            modelo.setValueAt(1+azar.nextInt(250), i-1, 3);
            modelo.setValueAt(+azar.nextInt(250), i-1, 4);
        }
        
         switch(azar.nextInt(8))
        {
            case 0: jRadioAmarillo.doClick();
            break;
            case 1: jRadioAzul.doClick();
            break;
            case 2: jRadioNaranja.doClick();
            break;
            case 3: jRadioRosa.doClick();
            break;
            case 4: jRadioRojo.doClick();
            break;
            case 5: jRadioVerde.doClick();
            break;
            case 6: jRadioGris.doClick();
            break;
            case 7: jRadioCyan.doClick();
            break;
                
        }
    }//GEN-LAST:event_jButAleatorioActionPerformed

    private void jButDibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDibujarActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(jSpinDibujar.getValue()+"")<=Integer.parseInt(jSpinNumero.getValue()+""))
        {
        creador(Integer.parseInt(jSpinDibujar.getValue()+"")-1);
        jSpinDibujar.setValue(Integer.parseInt(jSpinDibujar.getValue()+"")+1);
        }
        else
            jSpinDibujar.setValue(1);
     
    }//GEN-LAST:event_jButDibujarActionPerformed

    private void jRadioCyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCyanActionPerformed
        // TODO add your handling code here:
        for(int i=0; i < Integer.parseInt(jSpinNumero.getValue()+""); i++)
        modelo.setValueAt("Cyan", i, 5);
    }//GEN-LAST:event_jRadioCyanActionPerformed

    private void jRadioAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAzulActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<Integer.parseInt(jSpinNumero.getValue()+""); i++)
            modelo.setValueAt("Azul", i, 5);
    }//GEN-LAST:event_jRadioAzulActionPerformed

    private void jRadioRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRosaActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<Integer.parseInt(jSpinNumero.getValue()+""); i++)
            modelo.setValueAt("Rosa", i, 5);
    }//GEN-LAST:event_jRadioRosaActionPerformed

    private void jRadioAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAmarilloActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<Integer.parseInt(jSpinNumero.getValue()+""); i++)
            modelo.setValueAt("Amarillo", i, 5);
    }//GEN-LAST:event_jRadioAmarilloActionPerformed

    private void jRadioRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRojoActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<Integer.parseInt(jSpinNumero.getValue()+""); i++)
            modelo.setValueAt("Rojo", i, 5);
    }//GEN-LAST:event_jRadioRojoActionPerformed

    private void jRadioVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioVerdeActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<Integer.parseInt(jSpinNumero.getValue()+""); i++)
            modelo.setValueAt("Verde", i, 5);
    }//GEN-LAST:event_jRadioVerdeActionPerformed

    private void jRadioGrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGrisActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<Integer.parseInt(jSpinNumero.getValue()+""); i++)
            modelo.setValueAt("Gris", i, 5);
    }//GEN-LAST:event_jRadioGrisActionPerformed

    private void jRadioNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNaranjaActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<Integer.parseInt(jSpinNumero.getValue()+""); i++)
            modelo.setValueAt("Naranja", i, 5);
    }//GEN-LAST:event_jRadioNaranjaActionPerformed

    private void jButAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAsignacionActionPerformed
        // TODO add your handling code here:
         jFrameVisualB asignacion = new jFrameVisualB (this);
        
        asignacion.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButAsignacionActionPerformed

    private void jMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevoActionPerformed
        // TODO add your handling code here:
        jSpinNumero.setValue(0);
        jPanelDibujar.repaint();
        jSpinDibujar.setValue(1);
        jSpinPosicion.setValue(0);
        jTextLadoX.setText("");
        jTextLadoX2.setText("");
        jTextLadoY.setText("");
        jTextLadoY2.setText("");
    }//GEN-LAST:event_jMenuNuevoActionPerformed

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
        // TODO add your handling code here:
        if(jfch.showSaveDialog(jLabel1)!=0)
        return;
        
        FileOutputStream fos = null;
        DataOutputStream dos = null;
        
        try{
            fos = new FileOutputStream(jfch.getSelectedFile());
            dos = new DataOutputStream(fos);
            
            dos.writeInt(modelo.getRowCount());
            
             for(int r=0; r<modelo.getRowCount(); r++) {
                 dos.writeInt(Integer.parseInt(modelo.getValueAt(r, 0)+ ""));
                 dos.writeInt(Integer.parseInt(modelo.getValueAt(r, 1)+ ""));
                 dos.writeInt(Integer.parseInt(modelo.getValueAt(r, 2)+ ""));
                 dos.writeInt(Integer.parseInt(modelo.getValueAt(r, 3)+ ""));
                 dos.writeInt(Integer.parseInt(modelo.getValueAt(r, 4)+ ""));
                 dos.writeUTF(modelo.getValueAt(r, 5)+"");             }
        } 
        catch (FileNotFoundException ex) {
            Logger.getLogger(jFrameVisual.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(jFrameVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        finally
        {
            try{
                if(dos != null)
                dos.close();
                
                if(fos != null)
                    fos.close();
                
            } catch (IOException ex) {
                Logger.getLogger(jFrameVisual.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void jSpinNumeroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinNumeroStateChanged
        // TODO add your handling code here:
        modelo.setRowCount(Integer.parseInt(jSpinNumero.getValue()+""));
    }//GEN-LAST:event_jSpinNumeroStateChanged

    private void jSpinLadosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinLadosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinLadosStateChanged

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
        // TODO add your handling code here:
        if(jfch.showOpenDialog(jLabel1)!=0)
            return;
        
        FileInputStream fis = null;
        DataInputStream dis = null;
        
        try{
            fis = new FileInputStream(jfch.getSelectedFile());
            dis = new DataInputStream(fis);
            
            int renglones = dis.readInt();
            
            jSpinNumero.setValue(renglones);
            
            for(int r=0; r<modelo.getRowCount(); r++) {
                 modelo.setValueAt(dis.readInt(), r, 0);
                 modelo.setValueAt(dis.readInt(), r, 1);
                 modelo.setValueAt(dis.readInt(), r, 2);
                 modelo.setValueAt(dis.readInt(), r, 3);
                 modelo.setValueAt(dis.readInt(), r, 4);
                 modelo.setValueAt(dis.readUTF(), r, 5);
        }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(jFrameVisual.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(jFrameVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        finally{
            try{
                if(dis !=null)
                    dis.close();
                
                if(fis !=null)
                    fis.close();
            }
            catch (IOException ex) {
                Logger.getLogger(jFrameVisual.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         
        
 
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Escoje Un Color, para poder continuar");
        jSpinNumero.setValue(8);
        Poligono lado = new Poligono();
        
        
        jTablePoligono.setValueAt(45, 0, 0);
        jTablePoligono.setValueAt(70, 0, 1);
        jTablePoligono.setValueAt(85, 0, 2);
        jTablePoligono.setValueAt(110, 0, 3);
        jTablePoligono.setValueAt(30, 0, 4);
        
        
        jTablePoligono.setValueAt(140, 1, 0);
        jTablePoligono.setValueAt(220, 1, 1);
        jTablePoligono.setValueAt(36, 1, 2);
        jTablePoligono.setValueAt(30, 1, 3);
        jTablePoligono.setValueAt(75, 1, 4);
        
        
        jTablePoligono.setValueAt(23, 2, 0);
        jTablePoligono.setValueAt(30, 2, 1);
        jTablePoligono.setValueAt(74, 2, 2);
        jTablePoligono.setValueAt(22, 2, 3);
        jTablePoligono.setValueAt(130, 2, 4);
        
        
        jTablePoligono.setValueAt(54, 3, 0);
        jTablePoligono.setValueAt(30, 3, 1);
        jTablePoligono.setValueAt(30, 3, 2);
        jTablePoligono.setValueAt(73, 3, 3);
        jTablePoligono.setValueAt(170, 3, 4);
        
        
        jTablePoligono.setValueAt(5, 4, 0);
        jTablePoligono.setValueAt(70, 4, 1);
        jTablePoligono.setValueAt(170, 4, 2);
        jTablePoligono.setValueAt(150, 4, 3);
        jTablePoligono.setValueAt(170, 4, 4);
        
        
        jTablePoligono.setValueAt(61, 5, 0);
        jTablePoligono.setValueAt(150, 5, 1);
        jTablePoligono.setValueAt(130, 5, 2);
        jTablePoligono.setValueAt(110, 5, 3);
        jTablePoligono.setValueAt(180, 5, 4);
        
        
        jTablePoligono.setValueAt(75, 6, 0);
        jTablePoligono.setValueAt(120, 6, 1);
        jTablePoligono.setValueAt(130, 6, 2);
        jTablePoligono.setValueAt(160, 6, 3);
        jTablePoligono.setValueAt(140, 6, 4);
        
        
        jTablePoligono.setValueAt(9, 7, 0);
        jTablePoligono.setValueAt(170, 7, 1);
        jTablePoligono.setValueAt(78, 7, 2);
        jTablePoligono.setValueAt(130, 7, 3);
        jTablePoligono.setValueAt(40, 7, 4);
        
        
        if(Integer.parseInt(jSpinDibujar.getValue()+"")<=Integer.parseInt(jSpinNumero.getValue()+""))
        {
        creador(Integer.parseInt(jSpinDibujar.getValue()+"")-1);
        jSpinDibujar.setValue(Integer.parseInt(jSpinDibujar.getValue()+"")+1);
        }
        else
            jSpinDibujar.setValue(1);
                                              

    }//GEN-LAST:event_jButEjemploActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButAleatorio;
    private javax.swing.JButton jButAsignacion;
    private javax.swing.JButton jButDibujar;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenuItem jMenuNuevo;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JTextPane jPanelDibujar;
    private javax.swing.JRadioButton jRadioAmarillo;
    private javax.swing.JRadioButton jRadioAzul;
    private javax.swing.JRadioButton jRadioCyan;
    private javax.swing.JRadioButton jRadioGris;
    private javax.swing.JRadioButton jRadioNaranja;
    private javax.swing.JRadioButton jRadioRojo;
    private javax.swing.JRadioButton jRadioRosa;
    private javax.swing.JRadioButton jRadioVerde;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinDibujar;
    private javax.swing.JSpinner jSpinNumero;
    private javax.swing.JSpinner jSpinPosicion;
    private javax.swing.JTable jTablePoligono;
    private javax.swing.JTextField jTextLadoX;
    private javax.swing.JTextField jTextLadoX2;
    private javax.swing.JTextField jTextLadoY;
    private javax.swing.JTextField jTextLadoY2;
    // End of variables declaration//GEN-END:variables
}
