/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_2019_02_01_aplicacionalumnosvisual;

import java.text.DecimalFormat;
import java.util.Random;

/**
 *
 * @author aa630
 */
public class jFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jFramePrincipal
     */
    public jFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextAlumno1 = new javax.swing.JTextField();
        jTextAsist1 = new javax.swing.JTextField();
        jTextTareas1 = new javax.swing.JTextField();
        jTextProy1 = new javax.swing.JTextField();
        jTextExamen1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextAlumno2 = new javax.swing.JTextField();
        jTextAsist2 = new javax.swing.JTextField();
        jTextTareas2 = new javax.swing.JTextField();
        jTextProy2 = new javax.swing.JTextField();
        jTextExamen2 = new javax.swing.JTextField();
        jTextAlumno3 = new javax.swing.JTextField();
        jTextAsist3 = new javax.swing.JTextField();
        jTextTareas3 = new javax.swing.JTextField();
        jTextProy3 = new javax.swing.JTextField();
        jTextExamen3 = new javax.swing.JTextField();
        jLabelPromAsist = new javax.swing.JLabel();
        jLabelPromProy = new javax.swing.JLabel();
        jLabelPromExamen = new javax.swing.JLabel();
        jLabelPromGeneral = new javax.swing.JLabel();
        jButCalcular = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jButBorrar = new javax.swing.JButton();
        jLabelPromTareas = new javax.swing.JLabel();
        jLabelCalif1 = new javax.swing.JLabel();
        jLabelCalif2 = new javax.swing.JLabel();
        jLabelCalif3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextTareas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTareas1ActionPerformed(evt);
            }
        });

        jTextProy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextProy1ActionPerformed(evt);
            }
        });

        jTextExamen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExamen1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Alumno");

        jLabel2.setText("Asist");

        jLabel3.setText("Tareas");

        jLabel4.setText("Proyectos");

        jLabel5.setText("Examen");

        jLabel6.setText("CALIFICACION:");

        jTextTareas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTareas2ActionPerformed(evt);
            }
        });

        jTextProy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextProy2ActionPerformed(evt);
            }
        });

        jTextExamen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExamen2ActionPerformed(evt);
            }
        });

        jTextTareas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTareas3ActionPerformed(evt);
            }
        });

        jTextProy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextProy3ActionPerformed(evt);
            }
        });

        jTextExamen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExamen3ActionPerformed(evt);
            }
        });

        jLabelPromAsist.setBackground(new java.awt.Color(255, 255, 102));
        jLabelPromAsist.setOpaque(true);

        jLabelPromProy.setBackground(new java.awt.Color(255, 255, 102));
        jLabelPromProy.setOpaque(true);

        jLabelPromExamen.setBackground(new java.awt.Color(255, 255, 102));
        jLabelPromExamen.setOpaque(true);

        jLabelPromGeneral.setBackground(new java.awt.Color(255, 51, 51));
        jLabelPromGeneral.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPromGeneral.setOpaque(true);

        jButCalcular.setText("CALCULAR");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButAleatorios.setText("ALEATORIOS");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButBorrar.setText("BORRAR");
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });

        jLabelPromTareas.setBackground(new java.awt.Color(255, 255, 102));
        jLabelPromTareas.setOpaque(true);

        jLabelCalif1.setBackground(new java.awt.Color(102, 255, 255));
        jLabelCalif1.setOpaque(true);

        jLabelCalif2.setBackground(new java.awt.Color(102, 255, 255));
        jLabelCalif2.setOpaque(true);

        jLabelCalif3.setBackground(new java.awt.Color(102, 255, 255));
        jLabelCalif3.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel4)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextAlumno2)
                                    .addComponent(jTextAlumno1)
                                    .addComponent(jTextAlumno3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextAsist2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(jTextAsist1)
                                    .addComponent(jTextAsist3)
                                    .addComponent(jLabelPromAsist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextTareas1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                            .addComponent(jTextTareas2)
                                            .addComponent(jTextTareas3))
                                        .addGap(41, 41, 41))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabelPromTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(31, 31, 31)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextProy1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(jTextProy2)
                                    .addComponent(jTextProy3)
                                    .addComponent(jLabelPromProy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextExamen2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextExamen3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelPromExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jButBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jLabelPromGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCalif1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCalif2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCalif3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAsist1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTareas1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextProy1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCalif1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextAsist2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextTareas2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextProy2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextExamen2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCalif2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextAsist3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextTareas3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextProy3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextExamen3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCalif3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPromAsist, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPromProy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPromExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPromGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPromTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButAleatorios, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addComponent(jButBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButCalcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextTareas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTareas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTareas1ActionPerformed

    private void jTextProy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextProy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProy1ActionPerformed

    private void jTextExamen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExamen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExamen1ActionPerformed

    private void jTextTareas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTareas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTareas2ActionPerformed

    private void jTextProy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextProy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProy2ActionPerformed

    private void jTextExamen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExamen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExamen2ActionPerformed

    private void jTextTareas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTareas3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTareas3ActionPerformed

    private void jTextProy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextProy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProy3ActionPerformed

    private void jTextExamen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExamen3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExamen3ActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        
        String[] nom = {"Juan","Maria","Luis","Diana","martha","javier","cesar","julia","pedro","fernando"};
        String [] ape = {"Gomez","perez","Montes","Mendez","Flores","Blanco","Marin","Serna","Martinez","Candela"};
        
        jTextAlumno1.setText(nom[azar.nextInt(nom.length)]+" "+ape[azar.nextInt(ape.length)]);
        jTextAlumno2.setText(nom[azar.nextInt(nom.length)]+" "+ape[azar.nextInt(ape.length)]);
        jTextAlumno3.setText(nom[azar.nextInt(nom.length)]+" "+ape[azar.nextInt(ape.length)]);
        
        jTextAsist1.setText(40+azar.nextInt(61)+""); //40 a 100
        jTextAsist2.setText(40+azar.nextInt(61)+""); //40 a 100
        jTextAsist3.setText(40+azar.nextInt(61)+""); //40 a 100
        
        jTextTareas1.setText(40+azar.nextInt(61)+"");
        jTextTareas2.setText(40+azar.nextInt(61)+"");
        jTextTareas3.setText(40+azar.nextInt(61)+"");
        
        jTextProy1.setText(40+azar.nextInt(61)+"");
        jTextProy2.setText(40+azar.nextInt(61)+"");
        jTextProy3.setText(40+azar.nextInt(61)+"");
        
        jTextExamen1.setText(40+azar.nextInt(61)+"");
        jTextExamen2.setText(40+azar.nextInt(61)+"");
        jTextExamen3.setText(40+azar.nextInt(61)+"");
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        // TODO add your handling code here:
        jTextAlumno1.setText("");
        jTextAlumno2.setText("");
        jTextAlumno3.setText("");
        
        jTextAsist1.setText("");
        jTextAsist2.setText("");
        jTextAsist3.setText("");
        
        jTextTareas1.setText("");
        jTextTareas2.setText("");
        jTextTareas3.setText("");
        
        jTextProy1.setText("");
        jTextProy2.setText("");
        jTextProy3.setText("");
        
        jTextExamen1.setText("");
        jTextExamen2.setText("");
        jTextExamen3.setText("");
        
        jLabelPromAsist.setText("");
        jLabelPromTareas.setText("");
        jLabelPromProy.setText("");
        jLabelPromExamen.setText("");
        
        jLabelPromGeneral.setText("");
        
        jLabelCalif1.setText("");
        jLabelCalif2.setText("");
        jLabelCalif3.setText("");
    }//GEN-LAST:event_jButBorrarActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        DecimalFormat f = new DecimalFormat("###.00");
        //atributos
        String nombre;
        int asist, tareas, proy, examen;
        
        nombre = jTextAlumno1.getText();
        asist = Integer.parseInt(jTextAsist1.getText());
        tareas = Integer.parseInt(jTextTareas1.getText());
        proy = Integer.parseInt(jTextProy1.getText());
        examen = Integer.parseInt(jTextExamen1.getText());
        //PARA UN SOLO ALUMNO:
        Alumno uno = new Alumno();
        
        uno.setNombre(nombre);
        uno.setAsistencias(asist);
        uno.setTareas(tareas);
        uno.setProyectos(proy);
        uno.setExamen(examen);
        
        jLabelCalif1.setText(f.format(uno.calificacion())); //se elige la primera opcion con cadena y object y no es necesario poner cadena 
        //SEGUNDO ALUMNO
        Alumno dos = new Alumno(jTextAlumno2.getText(),
                                 Integer.parseInt(jTextAsist2.getText()),
                                 Integer.parseInt(jTextTareas2.getText()),                                      
                                 Integer.parseInt(jTextProy2.getText()),
                                 Integer.parseInt(jTextExamen2.getText()) );
        jLabelCalif2.setText(f.format(dos.calificacion()));
        //TERCER CONSTRUCTOS O ALUMNO 3
        Alumno tres = new Alumno(uno);
        
        tres.setNombre(jTextAlumno3.getText());
        //actuializamos esa informacion con los datos aleatorios de alumno 3:
        tres.setAsistencias(Integer.parseInt(jTextAsist3.getText()));
        tres.setTareas(Integer.parseInt(jTextTareas3.getText()));
        tres.setProyectos(Integer.parseInt(jTextProy3.getText()));
        tres.setExamen(Integer.parseInt(jTextExamen3.getText()));
        
        jLabelCalif3.setText(f.format(tres.calificacion())); //aqui saldra el mismo resultado del alumno 1
        
        double promAsist, promTareas, promProy, promExamen, promGeneral;
        
        promAsist=(uno.getAsistencias() + dos.getAsistencias() + tres.getAsistencias())/3.0;
        promTareas=(uno.getTareas() + dos.getTareas() + tres.getTareas())/3.0;
        promProy =(uno.getProyectos() + dos.getProyectos() + tres.getProyectos())/3.0;
        promExamen =(uno.getExamen() + dos.getExamen() + tres.getExamen())/3.0;
        
        promGeneral = (uno.calificacion() + dos.calificacion() + tres.calificacion())/3.0;
        
        jLabelPromAsist.setText(f.format(promAsist));
        jLabelPromTareas.setText(f.format(promTareas));
        jLabelPromProy.setText(f.format(promProy));
        jLabelPromExamen.setText(f.format(promExamen));
        jLabelPromGeneral.setText(f.format(promGeneral));
        
    }//GEN-LAST:event_jButCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCalif1;
    private javax.swing.JLabel jLabelCalif2;
    private javax.swing.JLabel jLabelCalif3;
    private javax.swing.JLabel jLabelPromAsist;
    private javax.swing.JLabel jLabelPromExamen;
    private javax.swing.JLabel jLabelPromGeneral;
    private javax.swing.JLabel jLabelPromProy;
    private javax.swing.JLabel jLabelPromTareas;
    private javax.swing.JTextField jTextAlumno1;
    private javax.swing.JTextField jTextAlumno2;
    private javax.swing.JTextField jTextAlumno3;
    private javax.swing.JTextField jTextAsist1;
    private javax.swing.JTextField jTextAsist2;
    private javax.swing.JTextField jTextAsist3;
    private javax.swing.JTextField jTextExamen1;
    private javax.swing.JTextField jTextExamen2;
    private javax.swing.JTextField jTextExamen3;
    private javax.swing.JTextField jTextProy1;
    private javax.swing.JTextField jTextProy2;
    private javax.swing.JTextField jTextProy3;
    private javax.swing.JTextField jTextTareas1;
    private javax.swing.JTextField jTextTareas2;
    private javax.swing.JTextField jTextTareas3;
    // End of variables declaration//GEN-END:variables
}
