/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_2019_03_27_aplicacionnominaempleados;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aa630
 */
public class JFrameReporte extends javax.swing.JFrame {

    /**
     * Creates new form JFrameReporte
     */
    
    //atributos del frame:
    JFrameMenu jfMenu;
    //referencia de empleados:
    Empleado []copia;
    DefaultTableModel modelo;
    public JFrameReporte(JFrameMenu jfm) {
        initComponents();
        //constructor
        jfMenu = jfm;
        
        jLabEmpReg.setText(jfMenu.getEmpleadosRegistrados()+""); 
        
        copia = new Empleado[jfMenu.getEmpleadosRegistrados()];
        
        modelo =(DefaultTableModel)jTableEmpleados.getModel();
        modelo.setRowCount(copia.length);
        
        for(int i=0; i< copia.length; i++)
            copia[i] = jfMenu.getEmpleado(i); //metodo del frameMenu. 
        
        mostrar();
    }
    //metodos propios 
    public void mostrar()
    {
        double total =0; //para contabilizar
        for (int r = 0; r < copia.length; r++) 
        {
            for (int c = 0; c <modelo.getColumnCount(); c++) //para limpiar la informacion y no se almacene donde mismo
                modelo.setValueAt(null, r, c);
           
            modelo.setValueAt(copia[r].getNumero(), r, 0);
            modelo.setValueAt(copia[r].getNombre(), r, 1);
            
            modelo.setValueAt(copia[r].sueldo(), r, 9);
            
            if(copia[r] instanceof Taller) //si copia es una instancia de taller 
            {
                Taller tal = (Taller)copia[r];  //el objeto copia se esta incluyendo al objeto de taller 
                
                modelo.setValueAt(tal.getPiezas(), r, 2);
                modelo.setValueAt(tal.getPrecioUnitario(), r, 3);
            }
            
            if(copia[r] instanceof Ventas)
            {
                Ventas ven = (Ventas)copia[r];  
                
                modelo.setValueAt(ven.getVentasTotales(), r, 4);
                modelo.setValueAt(ven.getComision(), r, 5);
            }
            
            if(copia[r] instanceof Administrativo)
            {
                Administrativo adm = (Administrativo)copia[r]; //esta misma referencia se esta pasando a copia
                
                modelo.setValueAt(adm.getDiasTrabajados(), r, 6);
                modelo.setValueAt(adm.getSueldoDiario(), r, 7);
            }   
            
            if(copia[r] instanceof Ejecutivo)
            {
                Ejecutivo eje = (Ejecutivo)copia[r]; //esta misma referencia se esta pasando a copia
                
                modelo.setValueAt(eje.getDiasTrabajados(), r, 6);
                modelo.setValueAt(eje.getSueldoDiario(), r, 7);
                modelo.setValueAt(eje.getBono(), r, 8);
            }   
           
            total+= copia[r].sueldo();
        }
        jLabTotal.setText(total+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabEmpReg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jButSueldo = new javax.swing.JButton();
        jButAlfabetico = new javax.swing.JButton();
        jButOriginal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButRegresar.setText("REGRESAR");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("EMPLEADOS REGISTRADOS: ");

        jLabEmpReg.setBackground(new java.awt.Color(204, 204, 204));
        jLabEmpReg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabEmpReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabEmpReg.setOpaque(true);

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUM", "Nombre", "Piezas", "Precio Uni$", "Ventas$", "%Comision", "Dias Trab", "Sueldo Dias", "Bono $", "Sueldo Base"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableEmpleados.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        jButSueldo.setText("POR SUELDO");
        jButSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSueldoActionPerformed(evt);
            }
        });

        jButAlfabetico.setText("ALFABETICO");
        jButAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlfabeticoActionPerformed(evt);
            }
        });

        jButOriginal.setText("ORDEN ORIGINAL");
        jButOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOriginalActionPerformed(evt);
            }
        });

        jLabel1.setText("TOTAL:");

        jLabTotal.setBackground(new java.awt.Color(204, 255, 255));
        jLabTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabTotal.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabEmpReg, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButRegresar)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jButSueldo)
                        .addGap(50, 50, 50)
                        .addComponent(jButAlfabetico)
                        .addGap(40, 40, 40)
                        .addComponent(jButOriginal)
                        .addGap(0, 237, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButAlfabetico)
                            .addComponent(jButOriginal)
                            .addComponent(jButSueldo))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButRegresar)
                    .addComponent(jLabEmpReg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        // TODO add your handling code here:
        dispose(); //quita el registro de la memoria el mismo objeto lo elimina 

        jfMenu.getEtiqueta().setBackground(Color.BLUE); //REFERENCIA DE LA ETIQUETA DE MENU

        jfMenu.setVisible(true); //se pone visible despues que se registra
    }//GEN-LAST:event_jButRegresarActionPerformed

    private void jButOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOriginalActionPerformed
        // TODO add your handling code here:
        //no ordena solo copia los elementos del arreglo copia:
        for(int i=0; i< copia.length; i++)
            copia[i] = jfMenu.getEmpleado(i); //metodo del frameMenu. 
        
        mostrar();
    }//GEN-LAST:event_jButOriginalActionPerformed

    private void jButSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSueldoActionPerformed
        // TODO add your handling code here:
        //se puede ordenar porque es en base a un solo objeto 
        //y lo que se ordena es solo las referencia del objeto:
        for (int i = 0; i <copia.length -1; i++)
            for (int j = i+1; j < copia.length; j++)
            {
                if(copia[i].sueldo() < copia[j].sueldo())
                {
                    Empleado aux =copia[i];
                    copia[i] = copia[j];
                    copia[j] = aux;
                }
            }
        
        mostrar();
            
        
    }//GEN-LAST:event_jButSueldoActionPerformed

    private void jButAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlfabeticoActionPerformed
        // TODO add your handling code here:
        //y lo que se ordena es solo las referencia del objeto:
        for (int i = 0; i <copia.length -1; i++)
            for (int j = i+1; j < copia.length; j++)
            {
                if(copia[i].getNombre().compareTo(copia[j].getNombre())>0)
                {
                    Empleado aux =copia[i];
                    copia[i] = copia[j];
                    copia[j] = aux;
                }
            }
        
        mostrar();
    }//GEN-LAST:event_jButAlfabeticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameReporte(new JFrameMenu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAlfabetico;
    private javax.swing.JButton jButOriginal;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JButton jButSueldo;
    private javax.swing.JLabel jLabEmpReg;
    private javax.swing.JLabel jLabTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
