/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_2019_03_15_aplicacionhorario;


import Utilerias.JTable.ColorCeldas;
import java.awt.Color;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aa629
 */
public class JFrameAsistencia extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAsistencia
     */
    private DefaultTableModel modelo;
    private Random azar = new Random();
             
    public JFrameAsistencia() {
        initComponents();
        
        modelo = (DefaultTableModel)jTableEmpleados.getModel();
    
        jTableEmpleados.setShowGrid(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinEmpleados = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButAleatorios = new javax.swing.JButton();
        jButCalcular = new javax.swing.JButton();
        jButArregloFrame = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButParalelos = new javax.swing.JButton();
        jButPintar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jLabel1.setText("NUMERO DE EMPLEADOS:");

        jSpinEmpleados.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinEmpleadosStateChanged(evt);
            }
        });

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre:", "Hras:", "Min:", "Seg:", "Hras:", "Min:", "Seg:", "TiempoTrabajado:"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(0).setPreferredWidth(320);
            jTableEmpleados.getColumnModel().getColumn(7).setPreferredWidth(180);
        }

        jLabel2.setBackground(new java.awt.Color(0, 204, 255));
        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENTRADA");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(0, 204, 255));
        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SALIDA");
        jLabel3.setOpaque(true);

        jLabTotal.setBackground(new java.awt.Color(0, 204, 255));
        jLabTotal.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabTotal.setText(" ");
        jLabTotal.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Bauhaus 93", 0, 11)); // NOI18N
        jLabel5.setText("TOTAL:");

        jButAleatorios.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jButAleatorios.setText("ALEATORIOS");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButCalcular.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jButCalcular.setText("CALCULAR");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButArregloFrame.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jButArregloFrame.setText("ARREGLO EN EL FRAME");
        jButArregloFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButArregloFrameActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jButton1.setText("ARREGLO ENCAPSULADO ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButParalelos.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jButParalelos.setText("ARREGLO PARALELOS");
        jButParalelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButParalelosActionPerformed(evt);
            }
        });

        jButPintar.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jButPintar.setText("PINTAR");
        jButPintar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPintarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButParalelos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButPintar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButArregloFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(220, 220, 220)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jSpinEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(133, 133, 133)
                                    .addComponent(jButAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButCalcular))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButAleatorios)
                    .addComponent(jButCalcular)
                    .addComponent(jLabel1)
                    .addComponent(jSpinEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabTotal)
                    .addComponent(jLabel5)
                    .addComponent(jButArregloFrame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButPintar)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButParalelos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        String[] nom = {"Quijote","San Fermin","Don Venancio","Sancho Panza"}; 
        
        for(int r=0; r<modelo.getRowCount();r++)
        {
            
            modelo.setValueAt(nom[azar.nextInt(nom.length)], r, 0);
            modelo.setValueAt(7+azar.nextInt(3), r, 1);
            modelo.setValueAt(azar.nextInt(60), r, 2);
            modelo.setValueAt(azar.nextInt(60), r, 3);
            
            modelo.setValueAt(15+azar.nextInt(3), r, 4);
            modelo.setValueAt(azar.nextInt(60), r, 5);
            modelo.setValueAt(azar.nextInt(60), r, 6);
            
            
        

        }
            
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        Horario entrada, salida, tiempoTrabajado;
        
        Horario total = new Horario();
        
        for(int r = 0; r<modelo.getRowCount();r++)
        {
            entrada = new Horario((int)modelo.getValueAt(r, 1),
                                  (int)modelo.getValueAt(r, 2),
                                  (int)modelo.getValueAt(r,3));
            
            salida = new Horario(Integer.parseInt(modelo.getValueAt(r, 4)+""),
                                Integer.parseInt(modelo.getValueAt(r, 5)+""),
                                Integer.parseInt(modelo.getValueAt(r,6)+""));
            
            tiempoTrabajado = salida.resta(entrada);
            
            modelo.setValueAt(tiempoTrabajado, r, 7);
        
            total = total.suma(tiempoTrabajado);
            
        
        }
        
        jLabTotal.setText(total+"");
        
        
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jSpinEmpleadosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinEmpleadosStateChanged
        // TODO add your handling code here:
        modelo.setRowCount((int)jSpinEmpleados.getValue());
        
    }//GEN-LAST:event_jSpinEmpleadosStateChanged

    private void jButArregloFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButArregloFrameActionPerformed
        // TODO add your handling code here:
        Empleado [] asistencia = new Empleado[modelo.getRowCount()];
        
        Horario ent = new Horario(), sal = new Horario();
        
        for (int r=0; r<modelo.getRowCount(); r++)
        {
           
            
            ent.setHoras((int)modelo.getValueAt(r, 1));
            ent.setMinutos((int)modelo.getValueAt(r, 2));
            ent.setSegundos((int)modelo.getValueAt(r, 3));
            
            sal.setHoras((int)modelo.getValueAt(r, 4));
            sal.setMinutos((int)modelo.getValueAt(r, 5));
            sal.setSegundos((int)modelo.getValueAt(r, 6));
            
            asistencia[r] = new Empleado(modelo.getValueAt(r, 0)+"",ent,sal);
            
        }
        
        
        for (int i=0; i <asistencia.length -1; i++)
            for (int j = i+1; j<asistencia.length; j++)
                if(asistencia[i].tiempoTrabajado().segundosTotales() > asistencia[j].tiempoTrabajado().segundosTotales())
                {
                    Empleado aux = asistencia[i];
                    asistencia[i] = asistencia[j];
                    asistencia[j] = aux;
                }
        
        for (int r=0; r<asistencia.length; r++)
        {
            modelo.setValueAt(asistencia[r].getNombre(), r, 0);
            modelo.setValueAt(asistencia[r].getEntrada().getHoras(), r, 1);
            modelo.setValueAt(asistencia[r].getEntrada().getMinutos(), r, 2);
            modelo.setValueAt(asistencia[r].getEntrada().getSegundos(), r, 3);
            
            modelo.setValueAt(asistencia[r].getSalida().getHoras(), r, 4);
            modelo.setValueAt(asistencia[r].getSalida().getMinutos(), r, 5);
            modelo.setValueAt(asistencia[r].getSalida().getSegundos(), r, 6);

            modelo.setValueAt(asistencia[r].tiempoTrabajado(), r, 7);
        }


    }//GEN-LAST:event_jButArregloFrameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Empresa soriana = new Empresa(modelo.getRowCount());
        
        for (int r = 0; r<modelo.getRowCount(); r++)
        {
            Horario ent = new Horario();
            Horario sal = new Horario();
            
            ent.setHoras((int)modelo.getValueAt(r, 1));
            ent.setMinutos((int)modelo.getValueAt(r, 2));
            ent.setSegundos((int)modelo.getValueAt(r, 3));
            
            sal.setHoras((int)modelo.getValueAt(r, 4));
            sal.setMinutos((int)modelo.getValueAt(r, 5));
            sal.setSegundos((int)modelo.getValueAt(r, 6));
            
            soriana.setEmpleado(new Empleado(modelo.getValueAt(r, 0)+"",ent,sal),r); // llenar el arreglo
        }
        
        soriana.ordenar();
        // regresar lo que esta en el arreglo
         for (int r = 0; r<modelo.getRowCount(); r++)
        {
            modelo.setValueAt(soriana.getEmpleado(r).getNombre(), r, 0);
            modelo.setValueAt(soriana.getEmpleado(r).getEntrada().getHoras(), r, 1);
            modelo.setValueAt(soriana.getEmpleado(r).getEntrada().getMinutos(), r, 2);
            modelo.setValueAt(soriana.getEmpleado(r).getEntrada().getSegundos(), r, 3);
            
            modelo.setValueAt(soriana.getEmpleado(r).getSalida().getHoras(), r, 4);
            modelo.setValueAt(soriana.getEmpleado(r).getSalida().getMinutos(), r, 5);
            modelo.setValueAt(soriana.getEmpleado(r).getSalida().getSegundos(), r, 6);

            modelo.setValueAt(soriana.getEmpleado(r).tiempoTrabajado(), r, 7);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButParalelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButParalelosActionPerformed
        // TODO add your handling code here:
        String [] nombres  = new String[modelo.getRowCount()];
        Horario [] entradas = new Horario[nombres.length];
        Horario [] salidas = new Horario [nombres.length];
        Horario [] tiempo = new Horario [nombres.length];
        
        for (int r = 0; r<modelo.getRowCount(); r++)
        {
            Horario ent = new Horario();
            Horario sal = new Horario();
            
            ent.setHoras((int)modelo.getValueAt(r, 1));
            ent.setMinutos((int)modelo.getValueAt(r, 2));
            ent.setSegundos((int)modelo.getValueAt(r, 3));
            
            sal.setHoras((int)modelo.getValueAt(r, 4));
            sal.setMinutos((int)modelo.getValueAt(r, 5));
            sal.setSegundos((int)modelo.getValueAt(r, 6));
          
            nombres[r] = modelo.getValueAt(r, 0)+"";
            entradas[r] = ent;
            salidas[r] = sal;
            tiempo [r] = sal.resta(ent);
        }

        for(int i = 0; i<tiempo.length-1; i++) // ordenando
            for(int j= i+1; j<tiempo.length; j++)
                if(tiempo[i].segundosTotales() > tiempo[j].segundosTotales())
                {
                    Horario aux = tiempo[i];
                    tiempo[i] = tiempo[j];
                    tiempo[j] = aux;
                    
                    aux = entradas[i]; // ordenar el arreglo de horario de entrada
                    entradas[i] = entradas[j];
                    entradas[j] = aux;
                    
                    aux = salidas[i];  // ordenar el arreglo de horario de salida
                    salidas[i] = salidas[j];
                    salidas[j] = aux;
                    
                    String auxn = nombres[i];   // ordenar el arreglo de los nombres
                    nombres[i] = nombres[j];
                    nombres[j] = auxn;
        
                }
        
        
        for(int r=0; r<modelo.getRowCount(); r++)
        {
            modelo.setValueAt(nombres[r], r, 0);
            
            modelo.setValueAt(entradas[r].getHoras(), r, 1);
            modelo.setValueAt(entradas[r].getMinutos(), r, 2);
            modelo.setValueAt(entradas[r].getSegundos(), r, 3);
            
            modelo.setValueAt(salidas[r].getHoras(), r, 4);
            modelo.setValueAt(salidas[r].getMinutos(), r, 5);
            modelo.setValueAt(salidas[r].getSegundos(), r, 6);
        
            modelo.setValueAt(tiempo[r], r, 7);
        }
        
        
        
        
    }//GEN-LAST:event_jButParalelosActionPerformed

    private void jButPintarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPintarActionPerformed
        // TODO add your handling code here:
        ColorCeldas celdas = new ColorCeldas(jTableEmpleados);  // Meterlo en un ciclo para pintarlo cmpleto
        
        celdas.addCelda(0, 0, Color.yellow);
        celdas.addCelda(modelo.getRowCount()-1, modelo.getColumnCount()-1, Color.RED);
        
        celdas.repaint(); 
        
    }//GEN-LAST:event_jButPintarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAsistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButArregloFrame;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButParalelos;
    private javax.swing.JButton jButPintar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinEmpleados;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
